import { KeyConfig, LayoutMode, KeyboardLanguage, OsMode } from './types';

export const FUNCTION_ROW: KeyConfig[] = [
  { code: 'Escape', label: 'Esc', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F1', label: 'F1', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F2', label: 'F2', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F3', label: 'F3', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F4', label: 'F4', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F5', label: 'F5', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F6', label: 'F6', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F7', label: 'F7', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F8', label: 'F8', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F9', label: 'F9', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F10', label: 'F10', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F11', label: 'F11', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'F12', label: 'F12', widthUnit: 1.0, flexGrow: 1.0 },
];

export const F_ROW_NAV_KEYS: KeyConfig[] = [
  { code: 'PrintScreen', label: 'PrtSc', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'ScrollLock', label: 'ScrLk', widthUnit: 1.0, flexGrow: 1.0 },
  { code: 'Pause', label: 'Pause', widthUnit: 1.0, flexGrow: 1.0 },
];

export function getSpanishLayout(osMode: OsMode): KeyConfig[][] {
  return [
    [
      { code: 'Backquote', label: 'º', shiftLabel: 'ª' },
      { code: 'Digit1', label: '1', shiftLabel: '!' },
      { code: 'Digit2', label: '2', shiftLabel: '"' },
      { code: 'Digit3', label: '3', shiftLabel: '·' },
      { code: 'Digit4', label: '4', shiftLabel: '$' },
      { code: 'Digit5', label: '5', shiftLabel: '%' },
      { code: 'Digit6', label: '6', shiftLabel: '&' },
      { code: 'Digit7', label: '7', shiftLabel: '/' },
      { code: 'Digit8', label: '8', shiftLabel: '(' },
      { code: 'Digit9', label: '9', shiftLabel: ')' },
      { code: 'Digit0', label: '0', shiftLabel: '=' },
      { code: 'Minus', label: "'", shiftLabel: '?' },
      { code: 'Equal', label: '¡', shiftLabel: '¿' },
      { code: 'Backspace', label: 'Backspace', widthUnit: 2.0, flexGrow: 2.0 },
    ],
    [
      { code: 'Tab', label: 'Tab', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'KeyQ', label: 'Q' },
      { code: 'KeyW', label: 'W' },
      { code: 'KeyE', label: 'E' },
      { code: 'KeyR', label: 'R' },
      { code: 'KeyT', label: 'T' },
      { code: 'KeyY', label: 'Y' },
      { code: 'KeyU', label: 'U' },
      { code: 'KeyI', label: 'I' },
      { code: 'KeyO', label: 'O' },
      { code: 'KeyP', label: 'P' },
      { code: 'BracketLeft', label: '`', shiftLabel: '^' },
      { code: 'BracketRight', label: '+', shiftLabel: '*' },
      { code: 'Backslash', label: 'ç', shiftLabel: 'Ç', widthUnit: 1.5, flexGrow: 1.5 },
    ],
    [
      { code: 'CapsLock', label: 'CapsLock', widthUnit: 1.8, flexGrow: 1.8 },
      { code: 'KeyA', label: 'A' },
      { code: 'KeyS', label: 'S' },
      { code: 'KeyD', label: 'D' },
      { code: 'KeyF', label: 'F' },
      { code: 'KeyG', label: 'G' },
      { code: 'KeyH', label: 'H' },
      { code: 'KeyJ', label: 'J' },
      { code: 'KeyK', label: 'K' },
      { code: 'KeyL', label: 'L' },
      { code: 'Semicolon', label: 'Ñ' },
      { code: 'Quote', label: '´', shiftLabel: '¨' },
      { code: 'Enter', label: 'Enter', widthUnit: 2.2, flexGrow: 2.2 },
    ],
    [
      { code: 'ShiftLeft', label: 'Shift', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'IntlBackslash', label: '<', shiftLabel: '>' },
      { code: 'KeyZ', label: 'Z' },
      { code: 'KeyX', label: 'X' },
      { code: 'KeyC', label: 'C' },
      { code: 'KeyV', label: 'V' },
      { code: 'KeyB', label: 'B' },
      { code: 'KeyN', label: 'N' },
      { code: 'KeyM', label: 'M' },
      { code: 'Comma', label: ',', shiftLabel: ';' },
      { code: 'Period', label: '.', shiftLabel: ':' },
      { code: 'Slash', label: '-', shiftLabel: '_' },
      { code: 'ShiftRight', label: 'Shift', widthUnit: 2.7, flexGrow: 2.7 },
    ],
    [
      {
        code: 'ControlLeft',
        label: osMode === 'mac' ? '⌃ Control' : 'Ctrl',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      {
        code: 'MetaLeft',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      {
        code: 'AltLeft',
        label: osMode === 'mac' ? '⌥ Option' : 'Alt',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      { code: 'Space', label: ' ', widthUnit: 6.6, flexGrow: 6.6 },
      {
        code: 'AltRight',
        label: osMode === 'mac' ? '⌥ Option' : 'AltGr',
        widthUnit: 2.1,
        flexGrow: 2.1,
      },
      {
        code: 'MetaRight',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 2.1,
        flexGrow: 2.1,
      },
    ],
  ];
}

export function getEnglishLayout(osMode: OsMode): KeyConfig[][] {
  return [
    [
      { code: 'Backquote', label: '`', shiftLabel: '~' },
      { code: 'Digit1', label: '1', shiftLabel: '!' },
      { code: 'Digit2', label: '2', shiftLabel: '@' },
      { code: 'Digit3', label: '3', shiftLabel: '#' },
      { code: 'Digit4', label: '4', shiftLabel: '$' },
      { code: 'Digit5', label: '5', shiftLabel: '%' },
      { code: 'Digit6', label: '6', shiftLabel: '^' },
      { code: 'Digit7', label: '7', shiftLabel: '&' },
      { code: 'Digit8', label: '8', shiftLabel: '*' },
      { code: 'Digit9', label: '9', shiftLabel: '(' },
      { code: 'Digit0', label: '0', shiftLabel: ')' },
      { code: 'Minus', label: '-', shiftLabel: '_' },
      { code: 'Equal', label: '=', shiftLabel: '+' },
      { code: 'Backspace', label: 'Backspace', widthUnit: 2.0, flexGrow: 2.0 },
    ],
    [
      { code: 'Tab', label: 'Tab', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'KeyQ', label: 'Q' },
      { code: 'KeyW', label: 'W' },
      { code: 'KeyE', label: 'E' },
      { code: 'KeyR', label: 'R' },
      { code: 'KeyT', label: 'T' },
      { code: 'KeyY', label: 'Y' },
      { code: 'KeyU', label: 'U' },
      { code: 'KeyI', label: 'I' },
      { code: 'KeyO', label: 'O' },
      { code: 'KeyP', label: 'P' },
      { code: 'BracketLeft', label: '[', shiftLabel: '{' },
      { code: 'BracketRight', label: ']', shiftLabel: '}' },
      { code: 'Backslash', label: '\\', shiftLabel: '|', widthUnit: 1.5, flexGrow: 1.5 },
    ],
    [
      { code: 'CapsLock', label: 'CapsLock', widthUnit: 1.8, flexGrow: 1.8 },
      { code: 'KeyA', label: 'A' },
      { code: 'KeyS', label: 'S' },
      { code: 'KeyD', label: 'D' },
      { code: 'KeyF', label: 'F' },
      { code: 'KeyG', label: 'G' },
      { code: 'KeyH', label: 'H' },
      { code: 'KeyJ', label: 'J' },
      { code: 'KeyK', label: 'K' },
      { code: 'KeyL', label: 'L' },
      { code: 'Semicolon', label: ';', shiftLabel: ':' },
      { code: 'Quote', label: "'", shiftLabel: '"' },
      { code: 'Enter', label: 'Enter', widthUnit: 2.2, flexGrow: 2.2 },
    ],
    [
      { code: 'ShiftLeft', label: 'Shift', widthUnit: 2.2, flexGrow: 2.2 },
      { code: 'KeyZ', label: 'Z' },
      { code: 'KeyX', label: 'X' },
      { code: 'KeyC', label: 'C' },
      { code: 'KeyV', label: 'V' },
      { code: 'KeyB', label: 'B' },
      { code: 'KeyN', label: 'N' },
      { code: 'KeyM', label: 'M' },
      { code: 'Comma', label: ',', shiftLabel: '<' },
      { code: 'Period', label: '.', shiftLabel: '>' },
      { code: 'Slash', label: '/', shiftLabel: '?' },
      { code: 'ShiftRight', label: 'Shift', widthUnit: 2.8, flexGrow: 2.8 },
    ],
    [
      {
        code: 'ControlLeft',
        label: osMode === 'mac' ? '⌃ Control' : 'Ctrl',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      {
        code: 'MetaLeft',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      {
        code: 'AltLeft',
        label: osMode === 'mac' ? '⌥ Option' : 'Alt',
        widthUnit: 1.4,
        flexGrow: 1.4,
      },
      { code: 'Space', label: ' ', widthUnit: 6.6, flexGrow: 6.6 },
      {
        code: 'AltRight',
        label: osMode === 'mac' ? '⌥ Option' : 'AltGr',
        widthUnit: 2.1,
        flexGrow: 2.1,
      },
      {
        code: 'MetaRight',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 2.1,
        flexGrow: 2.1,
      },
    ],
  ];
}

export function getSpanishLayout65(osMode: OsMode): KeyConfig[][] {
  return [
    [
      { code: 'Backquote', label: 'º', shiftLabel: 'ª' },
      { code: 'Digit1', label: '1', shiftLabel: '!' },
      { code: 'Digit2', label: '2', shiftLabel: '"' },
      { code: 'Digit3', label: '3', shiftLabel: '·' },
      { code: 'Digit4', label: '4', shiftLabel: '$' },
      { code: 'Digit5', label: '5', shiftLabel: '%' },
      { code: 'Digit6', label: '6', shiftLabel: '&' },
      { code: 'Digit7', label: '7', shiftLabel: '/' },
      { code: 'Digit8', label: '8', shiftLabel: '(' },
      { code: 'Digit9', label: '9', shiftLabel: ')' },
      { code: 'Digit0', label: '0', shiftLabel: '=' },
      { code: 'Minus', label: "'", shiftLabel: '?' },
      { code: 'Equal', label: '¡', shiftLabel: '¿' },
      { code: 'Backspace', label: 'Backspace', widthUnit: 2.0, flexGrow: 2.0 },
      { code: 'Delete', label: 'Del', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'Tab', label: 'Tab', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'KeyQ', label: 'Q' },
      { code: 'KeyW', label: 'W' },
      { code: 'KeyE', label: 'E' },
      { code: 'KeyR', label: 'R' },
      { code: 'KeyT', label: 'T' },
      { code: 'KeyY', label: 'Y' },
      { code: 'KeyU', label: 'U' },
      { code: 'KeyI', label: 'I' },
      { code: 'KeyO', label: 'O' },
      { code: 'KeyP', label: 'P' },
      { code: 'BracketLeft', label: '`', shiftLabel: '^' },
      { code: 'BracketRight', label: '+', shiftLabel: '*' },
      { code: 'Backslash', label: 'ç', shiftLabel: 'Ç', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'PageUp', label: 'PgUp', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'CapsLock', label: 'CapsLock', widthUnit: 1.8, flexGrow: 1.8 },
      { code: 'KeyA', label: 'A' },
      { code: 'KeyS', label: 'S' },
      { code: 'KeyD', label: 'D' },
      { code: 'KeyF', label: 'F' },
      { code: 'KeyG', label: 'G' },
      { code: 'KeyH', label: 'H' },
      { code: 'KeyJ', label: 'J' },
      { code: 'KeyK', label: 'K' },
      { code: 'KeyL', label: 'L' },
      { code: 'Semicolon', label: 'Ñ' },
      { code: 'Quote', label: '´', shiftLabel: '¨' },
      { code: 'Enter', label: 'Enter', widthUnit: 2.2, flexGrow: 2.2 },
      { code: 'PageDown', label: 'PgDn', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'ShiftLeft', label: 'Shift', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'IntlBackslash', label: '<', shiftLabel: '>' },
      { code: 'KeyZ', label: 'Z' },
      { code: 'KeyX', label: 'X' },
      { code: 'KeyC', label: 'C' },
      { code: 'KeyV', label: 'V' },
      { code: 'KeyB', label: 'B' },
      { code: 'KeyN', label: 'N' },
      { code: 'KeyM', label: 'M' },
      { code: 'Comma', label: ',', shiftLabel: ';' },
      { code: 'Period', label: '.', shiftLabel: ':' },
      { code: 'Slash', label: '-', shiftLabel: '_' },
      { code: 'ShiftRight', label: 'Shift', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'ArrowUp', label: '▲', widthUnit: 1.0, flexGrow: 0 },
      { code: 'End', label: 'End', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      {
        code: 'ControlLeft',
        label: osMode === 'mac' ? '⌃ Control' : 'Ctrl',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'MetaLeft',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'AltLeft',
        label: osMode === 'mac' ? '⌥ Option' : 'Alt',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      { code: 'Space', label: ' ', widthUnit: 6.5, flexGrow: 6.5 },
      {
        code: 'AltRight',
        label: osMode === 'mac' ? '⌥ Option' : 'AltGr',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'MetaRight',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.5,
        flexGrow: 1.5,
      },
      { code: 'ArrowLeft', label: '◀', widthUnit: 1.0, flexGrow: 0 },
      { code: 'ArrowDown', label: '▼', widthUnit: 1.0, flexGrow: 0 },
      { code: 'ArrowRight', label: '▶', widthUnit: 1.0, flexGrow: 0 },
    ],
  ];
}

export function getEnglishLayout65(osMode: OsMode): KeyConfig[][] {
  return [
    [
      { code: 'Backquote', label: '`', shiftLabel: '~' },
      { code: 'Digit1', label: '1', shiftLabel: '!' },
      { code: 'Digit2', label: '2', shiftLabel: '@' },
      { code: 'Digit3', label: '3', shiftLabel: '#' },
      { code: 'Digit4', label: '4', shiftLabel: '$' },
      { code: 'Digit5', label: '5', shiftLabel: '%' },
      { code: 'Digit6', label: '6', shiftLabel: '^' },
      { code: 'Digit7', label: '7', shiftLabel: '&' },
      { code: 'Digit8', label: '8', shiftLabel: '*' },
      { code: 'Digit9', label: '9', shiftLabel: '(' },
      { code: 'Digit0', label: '0', shiftLabel: ')' },
      { code: 'Minus', label: '-', shiftLabel: '_' },
      { code: 'Equal', label: '=', shiftLabel: '+' },
      { code: 'Backspace', label: 'Backspace', widthUnit: 2.0, flexGrow: 2.0 },
      { code: 'Delete', label: 'Del', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'Tab', label: 'Tab', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'KeyQ', label: 'Q' },
      { code: 'KeyW', label: 'W' },
      { code: 'KeyE', label: 'E' },
      { code: 'KeyR', label: 'R' },
      { code: 'KeyT', label: 'T' },
      { code: 'KeyY', label: 'Y' },
      { code: 'KeyU', label: 'U' },
      { code: 'KeyI', label: 'I' },
      { code: 'KeyO', label: 'O' },
      { code: 'KeyP', label: 'P' },
      { code: 'BracketLeft', label: '[', shiftLabel: '{' },
      { code: 'BracketRight', label: ']', shiftLabel: '}' },
      { code: 'Backslash', label: '\\', shiftLabel: '|', widthUnit: 1.5, flexGrow: 1.5 },
      { code: 'PageUp', label: 'PgUp', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'CapsLock', label: 'CapsLock', widthUnit: 1.8, flexGrow: 1.8 },
      { code: 'KeyA', label: 'A' },
      { code: 'KeyS', label: 'S' },
      { code: 'KeyD', label: 'D' },
      { code: 'KeyF', label: 'F' },
      { code: 'KeyG', label: 'G' },
      { code: 'KeyH', label: 'H' },
      { code: 'KeyJ', label: 'J' },
      { code: 'KeyK', label: 'K' },
      { code: 'KeyL', label: 'L' },
      { code: 'Semicolon', label: ';', shiftLabel: ':' },
      { code: 'Quote', label: "'", shiftLabel: '"' },
      { code: 'Enter', label: 'Enter', widthUnit: 2.2, flexGrow: 2.2 },
      { code: 'PageDown', label: 'PgDn', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      { code: 'ShiftLeft', label: 'Shift', widthUnit: 2.25, flexGrow: 2.25 },
      { code: 'KeyZ', label: 'Z' },
      { code: 'KeyX', label: 'X' },
      { code: 'KeyC', label: 'C' },
      { code: 'KeyV', label: 'V' },
      { code: 'KeyB', label: 'B' },
      { code: 'KeyN', label: 'N' },
      { code: 'KeyM', label: 'M' },
      { code: 'Comma', label: ',', shiftLabel: '<' },
      { code: 'Period', label: '.', shiftLabel: '>' },
      { code: 'Slash', label: '/', shiftLabel: '?' },
      { code: 'ShiftRight', label: 'Shift', widthUnit: 1.75, flexGrow: 1.75 },
      { code: 'ArrowUp', label: '▲', widthUnit: 1.0, flexGrow: 0 },
      { code: 'End', label: 'End', widthUnit: 1.0, flexGrow: 0 },
    ],
    [
      {
        code: 'ControlLeft',
        label: osMode === 'mac' ? '⌃ Control' : 'Ctrl',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'MetaLeft',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'AltLeft',
        label: osMode === 'mac' ? '⌥ Option' : 'Alt',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      { code: 'Space', label: ' ', widthUnit: 6.5, flexGrow: 6.5 },
      {
        code: 'AltRight',
        label: osMode === 'mac' ? '⌥ Option' : 'AltGr',
        widthUnit: 1.25,
        flexGrow: 1.25,
      },
      {
        code: 'MetaRight',
        label: osMode === 'mac' ? '⌘ Cmd' : 'Win ⊞',
        widthUnit: 1.5,
        flexGrow: 1.5,
      },
      { code: 'ArrowLeft', label: '◀', widthUnit: 1.0, flexGrow: 0 },
      { code: 'ArrowDown', label: '▼', widthUnit: 1.0, flexGrow: 0 },
      { code: 'ArrowRight', label: '▶', widthUnit: 1.0, flexGrow: 0 },
    ],
  ];
}

export function getTotalKeysCount(layoutMode: LayoutMode, keyboardLanguage: KeyboardLanguage): number {
  if (layoutMode === 'compact60') {
    return keyboardLanguage === 'es' ? 62 : 61;
  }
  if (layoutMode === 'compact') {
    return keyboardLanguage === 'es' ? 68 : 67;
  }
  if (layoutMode === 'tkl') {
    const baseMain = keyboardLanguage === 'es' ? 62 : 61;
    return baseMain + FUNCTION_ROW.length + F_ROW_NAV_KEYS.length + 10;
  }
  if (layoutMode === 'full') {
    const baseMain = keyboardLanguage === 'es' ? 62 : 61;
    return baseMain + FUNCTION_ROW.length + F_ROW_NAV_KEYS.length + 10 + 17;
  }
  return 87;
}
